@memoryGameId = 3828a8ae-01ef-4aa8-a164-c824577219f9
@cardId = 2f76631e-3754-477d-8424-6ffc7a33d9cd

POST http://localhost:8080/memory-game/{{memoryGameId}}/turn-card/{{cardId}}
Accept: application/json

